asp-mvc/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace asp_mvc.Models
{
    public class Book
    {
        public string ISBN { get; set; }
        public string Title { get; set; }
        public int YearPublished { get; set; }
        public int PublisherId { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }

        public Book(string isbn, string title, int yearPublished, int publisherId, double price, string description)
        {
            ISBN = isbn;
            Title = title;
            YearPublished = yearPublished;
            PublisherId = publisherId;
            Price = price;
            Description = description;
        }
    }
}

asp-mvc/Models/Customer.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace asp_mvc.Models
{
    public class Customer
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public bool IsSubscribedToNewsletter { get; set; }

        public MembershipType MembershipType { get; set; }

        [Display(Name = "Membership Type")]
        public byte MembershipTypeId { get; set; }

        [Display(Name = "Date of Birth")]
        //[Min18YearsIfAMember]
        public DateTime? Birthdate { get; set; }
    }

}

asp-mvc/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace asp_mvc.Models
{
    public class Genre
    {
        public byte Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

    }
    
}

asp-mvc/Models/MembershipType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace asp_mvc.Models
{
    public class MembershipType
    {
        public byte Id { get; set; }
        [Required]
        public string Name { get; set; }
        public short SignUpFee { get; set; }
        public byte DurationInMonths { get; set; }
        public byte DiscountRate { get; set; }

        public static readonly byte Unknown = 0;
        public static readonly byte PayAsYouGo = 1;
    }
}

asp-mvc/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace asp_mvc.Models
{
    public class Movie
    {

        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public Genre Genre { get; set; }

        [Display(Name = "Genre")]
        [Required]
        public byte GenreId { get; set; }

        public DateTime DateAdded { get; set; }

        [Display(Name = "Release Date")]
        public DateTime ReleaseDate { get; set; }

        [Display(Name = "Number in Stock")]
        [Range(1, 20)]
        public byte NumberInStock { get; set; }

        public byte NumberAvailable { get; set; }

    }
}

asp-mvc/Models/Rental.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace asp_mvc.Models
{
    public class Rental
    {
        public int Id { get; set; }

        [Required]
        public Customer Customer { get; set; }

        [Required]
        public Movie Movie { get; set; }

        public DateTime DateRented { get; set; }

        public DateTime? DateReturned { get; set; }
    }
}

asp-mvc/ViewModels/NewCustomerViewModel.cs
using asp_mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace asp_mvc.ViewModels
{
    public class NewCustomerViewModel
    {
        public IEnumerable<MembershipType> MembershipTypes { get; set; }
        public Customer Customer { get; set; }

        public int? Id { get; set; }

        public string Title
        {
            get
            {
                return Id != 0 ? "Edit Customer" : "New Customer";
            }
        }

        public NewCustomerViewModel()
        {
            Id = 0;
        }
    }
}

asp-mvc/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using asp_mvc.Models;

namespace asp_mvc.Controllers
{
    public class BooksController : Controller
    {

        private IList<Book> books = new List<Book>
        {
            new Book("B001", "Book 1", 2016, 200, 230, "Description 1"),
            new Book("B002", "Book 2", 2017, 201, 350, "Desscription 2"),
            new Book("B003", "Book 3", 2018, 200, 150, "Desscription 3"),
            new Book("B004", "Book 4", 2019, 202, 50, "Desscription 4"),
        };

        public ActionResult Index()
        {
            ViewBag.SectionTitle = "List of books";
            return View(books);
        }

        public ActionResult Details(string isbn)
        {
            Book book = null;
            foreach(var b in books)
            {
                if(b.ISBN.Equals(isbn))
                {
                    book = b;
                    break;
                }
            }

            ViewBag.Book = book;
            return View("BookDetails");
        }
    }
}

asp-mvc/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using asp_mvc.ViewModels;
using asp_mvc.Models;

namespace asp_mvc.Controllers
{
    public class CustomersController : Controller
    {
        private StoreContext _context;

        public CustomersController()
        {
            _context = new StoreContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            var customers = _context.Customers.Include(c => c.MembershipType).ToList();
            return View(customers);
        }

        public ActionResult Details(int id)
        {
            var customer = _context.Customers.Include(c => c.MembershipType).SingleOrDefault(c => c.Id == id);
            if (customer == null)
                return HttpNotFound();
            return View(customer);
        }

        public ActionResult New()
        {
            var memberships = _context.MembershipTypes.ToList();
            var viewModel = new NewCustomerViewModel
            {
                Customer = new Customer(),
                MembershipTypes = memberships
            };
            return View("Form", viewModel);
        }

        [HttpPost]
        public ActionResult Save(Customer customer)
        {
            if(customer.Id == 0)
            {
                _context.Customers.Add(customer);
            }
            else
            {
                var dbCustomer = _context.Customers.Single(c => c.Id == customer.Id);
                dbCustomer.Name = customer.Name;
                dbCustomer.Birthdate = customer.Birthdate;
                dbCustomer.IsSubscribedToNewsletter = customer.IsSubscribedToNewsletter;
                dbCustomer.MembershipTypeId = customer.MembershipTypeId;
            }
            _context.SaveChanges();
            return RedirectToAction("Index", "Customers");
        }

        public ActionResult Edit(int id)
        {
            var customer = _context.Customers.Include(c => c.MembershipType).SingleOrDefault(c => c.Id == id);
            if (customer == null)
                return HttpNotFound();

            var viewModel = new NewCustomerViewModel
            {
                Customer = customer,
                MembershipTypes = _context.MembershipTypes
            };
            return View("Form", viewModel);
        }
    }
}

asp-mvc/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using asp_mvc.Models;
using System.Data.Entity;

namespace asp_mvc.Controllers
{
    public class MoviesController : Controller
    {

        private StoreContext _context;

        public MoviesController()
        {
            _context = new StoreContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            var movies = _context.Movies.Include(m => m.Genre).ToList();
            return View(movies);
        }

        public ActionResult Details(int id)
        {
            var movie = _context.Movies.Include(m => m.Genre).SingleOrDefault(m => m.Id == id);
            if (movie == null)
                return HttpNotFound();
            return View(movie);
        }

        public ActionResult New()
        {
            return View("Form");
        }

        public ActionResult Edit()
        {
            return View("Form");
        }
    }
}

asp-mvc/Views/Books/BookDetails.cshtml
@using asp_mvc.Models
@model asp_mvc.Models.Book
@{
    ViewBag.Title = "BookDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Book Details</h2>

ISBN : @ViewBag.Book.ISBN <br/>
Title : @ViewBag.Book.Title <br/>
Published year : @ViewBag.Book.YearPublished

asp-mvc/Views/Books/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.SectionTitle</h2>

<table class="table table-striped">
    <tr><th>Title</th><th>Description</th><th>Price</th><th>Details</th></tr>
    @foreach (var book in Model)
    {
        <tr>
            <td>@book.Title</td>
            <td>@book.Description</td>
            <td>@book.Price</td>
            <td>
                @Html.ActionLink("Details", "Details", "Books", new { isbn = book.ISBN }, null)
            </td>

        </tr>
    }
</table>

<h2>Variables</h2>
@{
    var mql = "Qualité du Logiciel";
    var annee = "2018-2019";
}

<h3>Master : @mql</h3>
<br />
<h3>Année universitaure : @annee</h3>

<h2>Boucles</h2>

@{
    string[] members = { "Mohammed", "Salma", "Hicham" };
}
<ul>
    @foreach (var member in members)
    {
        <li>@member</li>
    }
</ul>
<ul>
    @{
        var i = 0;
        while (i < members.Length)
        {
            <li>@members[i]</li>
            i++;

        }
    }
</ul>

<h2>Instructions de controle</h2>

@{
    var message = "Good Morning";
    if (DateTime.Now.Hour > 12)
    {
        message = "Good Evening";
    }
}

<h3>@message</h3>


<h2>Objects</h2>
<table border="1">
    <tr>
        <th width="100px">Name</th>
        <td width="100px">Value</td>
    </tr>
    <tr>
        <td>Day</td>
        <td>@DateTime.Now.Day</td>
    </tr>
    <tr>
        <td>Hour</td>
        <td>@DateTime.Now.Hour</td>
    </tr>
</table>

asp-mvc/Views/Customers/Details.cshtml
@model asp_mvc.Models.Customer


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>


<ul>
    <li>Is subscribed to newsletter : @Model.IsSubscribedToNewsletter</li>
    <li>Membership type : @Model.MembershipType.Name</li>
    <li>membership discount : @Model.MembershipType.DiscountRate</li>
    @if (Model.Birthdate != null)
    {
        <li>Birthday : @Model.Birthdate</li>
    }

</ul>

asp-mvc/Views/Customers/Form.cshtml
@model asp_mvc.ViewModels.NewCustomerViewModel

@{
    /**/

    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = Model.Title;
}

<h2>@Model.Title</h2>

@using (Html.BeginForm("Save", "Customers"))
{


    <div class="form-group">
        @Html.LabelFor(m => m.Customer.Name)
        @Html.TextBoxFor(m => m.Customer.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Customer.Birthdate)
        @Html.TextBoxFor(m => m.Customer.Birthdate, "{0:d MMM yyyy}", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Customer.MembershipTypeId)
        @Html.DropDownListFor(m => m.Customer.MembershipTypeId, new SelectList(Model.MembershipTypes, "Id", "Name"), "Select a membership type", new { @class = "form-control" })
    </div>
    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.Customer.IsSubscribedToNewsletter) Subscribed to Newsletter ?
        </label>
    </div>


    <div class="form-group">
        @Html.HiddenFor(m => m.Customer.Id, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
}

asp-mvc/Views/Customers/Index.cshtml
@model IList<asp_mvc.Models.Customer>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customers</h2>


<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Membershipe type</th>
        <th>Details</th>
        <th>Update</th>
    </tr>
    @foreach (var customer in Model)
    {
    <tr>
        <td>@customer.Name</td>
        <td>@customer.MembershipType.Name</td>
        <td>@Html.ActionLink("Details", "Details", "Customers", new { id = customer.Id }, null)</td>
        <td>@Html.ActionLink("Edit", "Edit", "Customers", new { id = customer.Id }, null)</td>
    </tr>
    }
</table>

asp-mvc/Views/Movies/Details.cshtml
@model asp_mvc.Models.Movie


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<ul>
    <li>Genre : @Model.Genre.Name</li>
    <li>Add date : @Model.DateAdded</li>
    <li>Released year : @Model.ReleaseDate</li>
    <li>Number in stock : @Model.NumberInStock</li>
    <li>Available : @Model.NumberAvailable</li>
</ul>

asp-mvc/Views/Movies/Form.cshtml
@model asp_mvc.Models.Movie

@{
                /**/

                ViewBag.Title = "New";
                Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New movie</h2>

@using (Html.BeginForm("Create", "Movies"))
{

    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.NumberInStock)
        @Html.TextBoxFor(m => m.NumberInStock, new { @class = "form-control" })
    </div>

}

asp-mvc/Views/Movies/Index.cshtml
@model IList<asp_mvc.Models.Movie>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>

<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Genre</th>
        <th>Released year</th>
        <th>Number available</th>
        <th>Details</th>
    </tr>
    @foreach (var movie in Model)
    {
        <tr>
            <td>@movie.Name</td>
            <td>@movie.Genre.Name</td>
            <td>@movie.ReleaseDate</td>
            <td>@movie.NumberAvailable</td>
            <td>@Html.ActionLink("Details", "Details", "Movies", new { id = movie.Id }, null)</td>
         </tr> 
    }
</table>

asp-mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MQL-VID", "Index", "Movies", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Movies")</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Books", "Index", "Books")</li>
                    <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>